#:schema node_modules/wrangler/config-schema.json
name = "prio-conception"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[assets]
directory = "./public"

[vars]
CLOUDFLARE_ACCOUNT_ID = "efdcb0933eaac64f27c0b295039b28f2"
CLOUDFLARE_IMAGES_URL = "https://api.cloudflare.com/client/v4/accounts/efdcb0933eaac64f27c0b295039b28f2/images/v1"
